wtf:
  colors:
    background: "black"
    border:
      focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
  grid:
    # 10 cols
    columns: [16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
    # 10 rows
    rows: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
  refreshInterval: 1

  mods:
    ipinfo:
      type: "ipinfo"
      enabled: true
      title: "IP Address"
      position:
        top: 0
        left: 0
        height: 1
        width: 4
      refreshInterval: 300

    resourceusage:
      type: "resourceusage"
      enabled: true
      title: "System Resources"
      showCPU: true
      showMem: true
      showSwp: true
      cpuCombined: true
      position:
        top: 0
        left: 4
        height: 1
        width: 6
      refreshInterval: 1

    # docker:
    #   type: "docker"
    #   enabled: true
    #   title: "Docker"
    #   position:
    #     top: 2
    #     left: 0
    #     height: 3
    #     width: 6
    #   refreshInterval: 5

    yfinance:
      type: "yfinance"
      enabled: true
      title: "Yahoo Finance"
      symbols:
        - "AAPL"
        - "MSFT"
        - "GOOGL"
        - "AMZN"
        - "BTC-USD"
      position:
        top: 1
        left: 8
        height: 9
        width: 2
      refreshInterval: 120

    hackernews:
      type: "hackernews"
      enabled: true
      title: "Hacker News"
      numberOfStories: 10
      storyType: "top"
      position:
        top: 2
        left: 0
        height: 3
        width: 9
      refreshInterval: 900

    subreddit:
      type: "subreddit"
      enabled: true
      title: "Reddit"
      subreddits:
        - "roc_lang"
        - "gleamlang"
      numberOfPosts: 50
      sort: "hot"
      position:
        top: 5
        left: 0
        height: 3
        width: 9
      refreshInterval: 600

    feedreader:
      type: "feedreader"
      enabled: true
      title: "RSS Feeds"
      feeds:
        - "https://archlinux.org/news/feed/"
      feedLimit: 10
      position:
        top: 9
        left: 0
        height: 2
        width: 9
      refreshInterval: 600
